### ISSUE TITLE
npm publishについて

### ISSUE THREAD

**Issue by himanoa** [kanamone/js-scrambler#2]
パッケージをリリースするにあたって考えなきゃいけないこと

- CIでpublishする方法
- Changelog生成
- LICENSE

**Comment by naporin0624** [comment]
[changeset](https://github.com/changesets/changesets) がすき

この辺参考にできそう
https://github.com/honojs/middleware/blob/main/.changeset/config.json
https://github.com/honojs/middleware/blob/main/.github/workflows/release.yml
